theme: jekyll-theme-slate
title: Welcome to Hell, please enjoy your stay. you get a free cookie in the lobby from 3 - 7pm.
description: Feel free to die asap or you can live too if you want. you can even win 5 dollars if you compliment my new sunglasses!
